apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Release.Name }}-efs-sc
parameters:
  provisioningMode: efs-ap
  fileSystemId: "{{- .Values.efsFileSystemId }}"
  directoryPerms: "700"
  gidRangeStart: "1000"
  gidRangeEnd: "2000"
provisioner: "efs.csi.aws.com"